### ISSUE TITLE
[bug]: Unable to authenticate with github

### ISSUE THREAD

**Issue by LeKSuS-04** [firecamp-dev/firecamp#29]
**Describe the bug**
I'm unable to sign up with github. When I'm trying to do so, I get a blank html page with error message: `The username must not be containing any spaces`

**To Reproduce**
1. Go to https://firecamp.dev/
2. Press "Sign In or Sign Up in Firecamp ![image](https://github.com/firecamp-dev/firecamp/assets/74228258/a4264bd4-f770-4696-bca5-f28330b3bdc4)
3. Press "Continue with Github" 
![image](https://github.com/firecamp-dev/firecamp/assets/74228258/8c0ab3fb-068c-4248-b71d-09bbe099a50f)
4. Try to sign in with my Github account (lol)

**Expected behavior**
I expected to be signed in

**Screenshots**
![image](https://github.com/firecamp-dev/firecamp/assets/74228258/352f88de-1911-4f7b-b9d4-55955910d419)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version 115

**Additional context**

**Comment by shreya-gr** [comment]
@LeKSuS-04 thank you for reporting the issue. I appreciate it. My team will start resolving this bug and update you on the progress.

**Comment by Nishchit14** [comment]
The reason is that the username is containing the [`-` Hyphen, dash](https://www.webopedia.com/definitions/special-character/) special character. Currently, in Firecamp the username must not be containing any spaces or special characters. I am assuming the username is @LeKSuS-04 

We need to rethink this case. cc @shreya-gr (your one is also having `-` 😄  )
